package test;
/*
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
import codegen.GenPassword;

class GenPasswordTest {
	GenPassword genPassword = new GenPassword();

	@Test
	void testGenPassword() {
		int smallLetterCounter = 0, capitalLetterCounter = 0, 
				numberCounter = 0, specialCharCounter = 0, numberOfTests = 10000;

		for(int j = 0; j < numberOfTests; j++) {
			String password = genPassword.genPassword();
			char[] chars = password.toCharArray();
			for (int i = 0; i < chars.length; i++) {
				int currentChar = (int) chars[i];

				if(currentChar >= 97 && currentChar <= 122) {
					smallLetterCounter++;
				}
				else if(currentChar >= 65 && currentChar <= 90) {
					capitalLetterCounter++;
				}
				else if(currentChar >= 48 && currentChar <= 57) {
					numberCounter++;
				}
				else if (currentChar == 46 || currentChar == 45 || currentChar == 95 ||
						currentChar == 43 || currentChar == 33 ||
						currentChar == 63 || currentChar == 61) {
					specialCharCounter++;
				}
			}
		}
		if(smallLetterCounter == numberOfTests*2 && capitalLetterCounter == numberOfTests*2 && 
				numberCounter == numberOfTests && specialCharCounter == numberOfTests) {
		}
		else {
			fail("The autogenerated password does not fulfill the requirements");
		}
	}

}
*/